# Generated by Django 2.0.13 on 2019-09-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1_url',
            field=models.CharField(default='default_1.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_url',
            field=models.CharField(default='default_1.jpg', max_length=200),
        ),
    ]
