# Generated by Django 3.0.7 on 2020-12-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
